apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: tokped-sniper
type: Opaque
stringData:
  root-password: "changeme-root"   # change this
  password: "tokpedsniper"         # change this
  user: "tokpedsniper"
  database: "tokpedsniper"
