apiVersion: v1
kind: Secret
metadata:
    name: mariadb-secret
    namespace: tokped-sniper
type: Opaque
data:
    database: ENC[AES256_GCM,data:FEvWBNLgGCNhrSXERffAaQ==,iv:vcuJZMpSYZYDjZXzanfmtyqZrf0X4u6tw3mr3eXT04Y=,tag:WBpbsoWRhUXSeJQlUO7/qg==,type:str]
    password: ENC[AES256_GCM,data:DPFVriRW3eYco4XM/YUU9tP8Q/m7ULlr/brKFiDokJw=,iv:usW3Dfnb57PywfHrej91Np8IUcS0jmM9+sC8HR/UABM=,tag:pDxyUJJUawTIavK0uAlSsw==,type:str]
    root-password: ENC[AES256_GCM,data:A51CVrdDrq6wsaNYHRdJQYsm4NL2/3daPSPDKJXnMFc=,iv:ctr8vdZFB2O8WmkSuHNjYhhr2E+MZqh7Va5Lx5i4t0w=,tag:TVWnGaulT+X6CLKEIvp7UQ==,type:str]
    user: ENC[AES256_GCM,data:wmyugyE30prrR1YeSE+Pcw==,iv:Ijp1K5UzG1Rek0SFooncIyW8mPXHHvUJJJYdenB+Al4=,tag:vNw8LfK27e+JtJNkj1bTPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5RWRSVUhPajVueUlJWTJx
            bUJ0WU1HYmNuYmZ3T1ZzWFhzbEdJeHE1eDBZCmRnM3dzbmwxeXdacFBrZExFS1VC
            SmxYb2RIazZ3bEZ2Z0lqcy9yQlJheGsKLS0tICs3VGJ6RG01RUxMZFdud1AzS3Ev
            VTI0VVIxNk9NZUZJZHJIRWZQL05IWTgK4+qAUoJpWIf23BCZk89WBYXAaVhQtC46
            QNi0ZjYjaf6iyEewRpkRkRnIMBqQZhKYjb1LIq58QG8B8dWDRMiFFw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:17:37Z"
    mac: ENC[AES256_GCM,data:o+HZG3Sfk8Vd1wqHa0mCLGkcSuCYo2RoncETQBDFtygPpI9jFCkludLxkB9McNuxduYNG4WhZWJPJ21kDBAl4gIZI7I/SI7kpSVnGVp8YhI3v1e2ZmQu5RUZhYxVmE/sNZuW/jptYyH+pkqaEGfTZGPu2fl4jssjRTMrB+KaT4M=,iv:LaxnsPUMFgZc4V7u8i+kn3rsICtn6EY3rf3SvKfQWY4=,tag:LWFgMhddnphR3UrHRISRlA==,type:str]
    version: 3.13.3
