apiVersion: v1
kind: Secret
metadata:
    name: beatlesguessr-secret
    namespace: beatlesguessr
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:urEVhnRf0lWz5y4WwjwEfTGQ6Us=,iv:oLHe5jgOOQg2cwMDN3NacKh/eSuDAv3NaEYodNQBHcM=,tag:pPaSQjImucmbfO+Xoo2YQQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ebX0zjStyLNSuGGCs4NCTQWlzW3+tpVvz+ygXwfq+8zgiFvEVRxc3A==,iv:elH9Tr5JVmIJnfh2ZXCgZaOyy3Hm4OAYG6ky93MxZqM=,tag:a8oqpIs0YzQrV1tgP/6XMQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MWNMWGxiK2dBMFhGSHB6
            dnFDaDNXb3k0WFA5YjJ4S0JWb3QwNnBtWVQ0CmVUM1MrS1E3Ums1VGU3OUNNOHN6
            N2dPRHJ0N3JMckp1cExBcVRNQ1NZYU0KLS0tIHZOa3V2Ylh2VEc5SkM1WjR5T2Nn
            c3lpLzVHd3AvWnRaSXVyclVQYSt5SFUKXbW/huLunIF4Qsvf3ykXEmgp+RBMW+ci
            CsxxR4XSG8wv/KL4ZqCNCyyRXwMoEC/wJhsVvBsA6loRnHhn9wDN1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:27:22Z"
    mac: ENC[AES256_GCM,data:+6UnWPsMZPFvDWBVMUL/mvf7eUg1jMPflZYo0hRHSppXgf/kmqWcoV67kdTxb7dpzFpGqLKWWNS3lco2uHWe+bvKaY7kxOME+eaN8WuF8ND8G7Q700kFqBAwzgh/lCPSyG7tRaTt75ZVNF87QqvcV8Xr9nXQHpUh9KMquJ0tUeY=,iv:1bo+ucI7enVwPAfmAORICj3mqcSKwhIJWXi+mA70V9E=,tag:xhhXwTREb6zHOIyLB9EczA==,type:str]
    version: 3.13.3
