apiVersion: v1
kind: Secret
metadata:
    name: beatlesguessr-secret
    namespace: beatlesguessr
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:urEVhnRf0lWz5y4WwjwEfTGQ6Us=,iv:oLHe5jgOOQg2cwMDN3NacKh/eSuDAv3NaEYodNQBHcM=,tag:pPaSQjImucmbfO+Xoo2YQQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:ebX0zjStyLNSuGGCs4NCTQWlzW3+tpVvz+ygXwfq+8zgiFvEVRxc3A==,iv:elH9Tr5JVmIJnfh2ZXCgZaOyy3Hm4OAYG6ky93MxZqM=,tag:a8oqpIs0YzQrV1tgP/6XMQ==,type:str]
    BEATLESGUESSR_SES_ACCESS_KEY_ID: ENC[AES256_GCM,data:gN1yME7QHk2bSx4VWlozMpwYVq0=,iv:zSN7DXM8u83CdOMmkIKViE0Bzjj7G3pPnYguQEQ7y2w=,tag:SqrO2FGxfhiyiyRD5V6kgw==,type:str]
    BEATLESGUESSR_SES_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:RekYtGLLzpvMnQPYXCDKFokryonfDy03wqUH3oe46CT9Pt9WHPiVkQ==,iv:UNk+2lsfH+aFx2OYTnAmPPpNKNKmnQ6n2UdHA6ouyUM=,tag:yGdErBBQn5GQ2D5fLVDv3Q==,type:str]
    BEATLESGUESSR_RESEND_API_KEY: ENC[AES256_GCM,data:IAovFLlVlXCvQFqTtysiMXsYvQUj3bDxFlIVIofLdS9SEhvs,iv:2CjRlbrer7i8Y3giEIzvrUYb5iMpNiD0pqhci/CaIZU=,tag:luj8d4fMwjSQWT71pY58FQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MWNMWGxiK2dBMFhGSHB6
            dnFDaDNXb3k0WFA5YjJ4S0JWb3QwNnBtWVQ0CmVUM1MrS1E3Ums1VGU3OUNNOHN6
            N2dPRHJ0N3JMckp1cExBcVRNQ1NZYU0KLS0tIHZOa3V2Ylh2VEc5SkM1WjR5T2Nn
            c3lpLzVHd3AvWnRaSXVyclVQYSt5SFUKXbW/huLunIF4Qsvf3ykXEmgp+RBMW+ci
            CsxxR4XSG8wv/KL4ZqCNCyyRXwMoEC/wJhsVvBsA6loRnHhn9wDN1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-04T01:34:41Z"
    mac: ENC[AES256_GCM,data:WtUS9sS/5rnnfStGPYDA0aVKaqFqtI1lNNs/iWcgzXTYolzaSNvE9OLhoVfrdTMi+Uy/Lwj5srp5QTj6irfqVe3Lk9YJgk9nWzTZoNQJZi12ub/cvdAFXHWiGCNNk54ReXRv547DnFdRix5/67n2XE++N1NzetR3fHd9Nk6dd5o=,iv:cUgNmt7RUOij9XYxBDHqYhdREvtKWGaAZXWM3nbwRJA=,tag:5EzKNEMPsC4+vZ6b1tnozg==,type:str]
    version: 3.13.3
