apiVersion: v1
kind: Secret
metadata:
    name: beatlesguessr-backup-secret
    namespace: beatlesguessr
type: Opaque
stringData:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:QP5X0XgdhYpzGE0ntTjug6Rdv/Q=,iv:5iSnPmTFdfxC+KI/z5ks8SGofmrNcuLq+HWl/2CuRW4=,tag:CQg1h8mIEBFBIe77C0tDwA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:AAcHZ+TQyxJiHuf72yDctfVl0jchWihyCf2PmeHDWGUd9pF7RsNPlA==,iv:LAf9ve0aH6ovprswCqpv8lVqqj8a2O02MiFV46E9kG8=,tag:7I5Xsq5kIeLfZq/jn54HNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFWnV6TFZza0hGci85STBO
            NzdNMVZ4a3RScTg3SndqYW4vZEI1SGJhRWtvCnNpcU5PdzlLUTN2VktwUThtUUt0
            dFFqWGxyUEcwWjFxTU42VjIyVTBMVWcKLS0tIHA0eEZlb1cvYWpSdmIxUGhDcXR3
            d1FIMTN3RWIvaHo4QVhlNUhKSHEzQUUKS9F051Hlsu+pJPi9Kc5S4uvwJZk3Xa+K
            o2K8a5/WKXVofx2vW31n8Ou5/OpUM7ki1JkQBBywshj1hcc2Mg7onw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:27:30Z"
    mac: ENC[AES256_GCM,data:EzbyNOCYyqwEEd1QbnmkWDJ8ErbtSHZoaRb3Tgl6389cdi79GHzFsgYt85O9tOUCbsw78NswWiH3MxiI3SYMqXPWTV35tE+5yeUvz8UnFD/sNtJjihTDNlLbuuCx954vqJ9MMg9X7DnY+yLUG86aL5hPLVgEiKFAo59ziKpUM8U=,iv:czqQegS6TdiAX5cjzJ3uh/9Z2dcGKzKWDNukmh+4E3M=,tag:clMbaWymT8KeMi/WSt01hA==,type:str]
    version: 3.13.3
