apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: beatlesguessr
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:v8eVBx9JzWbC2UE9cl8h7jlTfYCpzQIKnjpLPoeLrSVw/QTP0ExwxD8MXeLkeELImD9XDd2nNxlkZiiBGiLSSYgnHH0Tc+TWIvf1nrOj48QGFEylletSB9r5n59TKVLVdG4YM2SYTMAg1ELNgvZK3cIQFcnf0LfIDF3nRaGj3e7A4dcJMBwGO0q1VDoa/CKbJZlKkal0xebvFVqvJh4BvlWKlXBMdhJX25nBd3Ub/Q0dS4dNSP1WaUUNv+FxOwh5tPOEmtJd+3ljNp8QVvHGnWNZlU1qATWOLqTAaLujQosunXZBVheqk41x00f19hrv,iv:gratvq1K4w6ENt2Ph+TIvVMGJuFr/Jpkake13scpYb0=,tag:MKsO6Z78udMWwPNe5kdoNg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQMkpJUU9rUW9FbGFMOFZZ
            Q2h0TVNtL1BLOExFZ1pTa21sQWo4M3JvSjJFCnZqY0JxNzgrUk5Uc2tRcW51S1Fv
            MU9hUXNCcndrUXpTZ1JqZWdFNGFRTDgKLS0tIHRwckxOQnBRV0FOTHF4NTdqMXRn
            SUVua3gzZE5FK2VFSGdOdkFpeWdaR00KzSR5AXJ7LWIOIkVqP3FkO8XWN5K85K5S
            wHlT8+VDQZc2cocY3r6EF3x0Uxll6LT4WYDstt4c7/xpnApCg7WTEA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:18:37Z"
    mac: ENC[AES256_GCM,data:CnswY4wNx/fhJ2ry1JX1weiaNJF3N057MG6p1jAwtgUujCmIxPlcoFLyrJlf/8kjgbxF6E+KdM4SxotWf/UCMIHbt0wzz01oTJ5VUMJvXwjD+MQAKp60uAdeQIkQyI91TjfumNWH+GwV0DhWNhgfRBn75ekbpZJqvqzYL4KbzSM=,iv:x0tu/LzYgfm4palKQyM4EbIzLPPJZIxdYO2gz+pw94w=,tag:ZGOA2G5QNnVNo38fVVKWTA==,type:str]
    version: 3.13.3
