apiVersion: v1
kind: Secret
metadata:
    name: healthcheck-secret
    namespace: beatlesguessr
type: Opaque
data:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:YcNK74nnAV8qn3YuVh0IorVi7AFPYLaZjIzSi2v1ZV/4Cow+78GukjyQGRXXAV9Es9rQwtzuuCuylc/xMuC1X0RfIPbCKf9+ESDFavjAqU3ZklZmYNQaJ0ezYErvKV2e6stTLQhIFbkwnpopulkN2K2Gtrne81aCb4bQ9PZoVO33PnRTzD//4o2prnA9iUwhs4E+vBoKCsC/eLLXMeupRs9R64w=,iv:E9YyrLk8h3yGMZiZIXv5fNUMc4KRbniI9mOCRG3Ie40=,tag:73OvgWRgSSes2kp2wo8UfA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiQnFPYXNmVEVvRURvNS9G
            djJNd3VyMEFRU0xHRmNGd0FIQVpjTFpOeTNFClR2VUxGZnM4b0tWSUFGcWVRd3lQ
            OS80bC9YcVVFMUd6cXhpZjNBdmFZUUUKLS0tIG83TXNaQ21zc2RNbG1DTFp4MTNs
            SVBSM0t3UzdrNkxEWVJWcGV1ekdwK3cKAlFBY3T65UL2e1ZEGPyS2SfbN8dODJFC
            Op97Faobmr7HJYLV9FOoIvRot3QEtTCxFwtxeJmx4wXXBDnZrkjfDA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-03T20:34:52Z"
    mac: ENC[AES256_GCM,data:/8CoJubx6FSNmep3QmEeP3skCAgnhGmeq6Ax3mAfEvn7VA/In2sjh6d1moVGefga/SsHk+WSE/gxSteCPMIpUXcapnet243HDKLVTrtgZ/VVbRQBj3Iaj11NY9VNPyu1iAaWVdbvKi9WeRLDRnis/vZ2P9IT7WegFF+C0cbAhR8=,iv:7lBxvgr25MdDNmgfpgQHRf3KKR0QjERXbtI1DzsuyAU=,tag:Cd4ZBzRTFBotln/xhdSVnw==,type:str]
    version: 3.13.3
