apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: tokped-sniper
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:JDleUC93bg4FGs53tTCHbN1dNrVQRs8gYeWUDmHwoXO74AzqFSMCaJp/BWZF8JhlkbVDmz1D4ZdzAgBPdvwRLLWY43tpOQJyZkWvC9dXQx8Rs58VDNYeGT2HGxEnRuH9DXyZ/ESb24D/ehEFgMfYNfWjKkPmoEnNA2my8aSch0aFiTqG7Q/fFVfIEPcJ3uwi4XyvYN0WWdvuA11HwPO0wa6/5432NoANBdHF51oEovYfEgXBcMdvamE3GrBtdw3RwpRLFgD3AJZUssmMRcTMoh1uhe9jNuJNXgqh8Ine1ZpBs4UQCuJR/cqJPq40LclH,iv:ZmzBTAGhta9uSJDt32t5Fy9nV/BZ4AOFxIvvo6G2D3c=,tag:8rwzYPA1+lXXrFT3ahbTJA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQOHlIaGd2UHdaTDRZdGt0
            aExyZ0xuWDlwUkJVT2c3bjMwRzhLTGFWVUJ3CjZGWEtZbWhReGs1R3NiVGxHYkpG
            WkxrcnFBbUlCdVJ1VFFiQ1EvSUx5bWsKLS0tIGhGQnZLYmdXN2Vndld4TGNHWUov
            elloZi9RcC9BaWRzN25rdUtKd1M1RlUKgAN4iY/dzVBQxHtxwnZj8rfrSH0Cqox1
            nF0u1lrHXkHjNxwVx/RU9Jtf+n3z78TY+R8gl7XBNuKfolkC61Tcew==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:17:37Z"
    mac: ENC[AES256_GCM,data:VaZRB5Y5XGRqGtjBj5bRB76Zn5gFjs32iu4xAb/dmzXez4pmiU6nn6patheE8VMdfHMFUqRh+oRa/83C/WxKFlU/z4oIOpOg5+AhlglYjmBQSs6YBUvlId3ExBit0Gt8mTCSG83hpDLKCsarflEv9N+Pyyzlpcl4sQp3g0u/UNQ=,iv:9641PBqYQ4O0Gl6csQnR9TaW7Rvzk/zTqxwYvfcuVrI=,tag:6FtTvL4WwMlNQFDaZlkYNA==,type:str]
    version: 3.13.3
