apiVersion: v1
kind: ConfigMap
metadata:
  name: bot-config
  namespace: tokped-sniper
data:
  SEARCH: '["kaset senandung yogyakarta","kaset aka","kaset bob tutupoly","kaset utje","kaset one dee","kaset giant step","kaset iis sugianto salah tingkah","kaset badai pasti berlalu","kaset superkid","kaset singing student","kaset aria","kaset bubi chen","kaset louise","speaker sony ss","kaset ragadi","kaset koes","kaset student power","kaset lclr","kaset lomba cipta","kaset sas","kaset pramaqua","kaset noor bersaudara","kaset harry roesli","kaset benny soebardja","kaset hidayat","kaset pohang","kaset mapajalos","kaset donas","kaset abimanyu","kaset deddy stanzah","kaset rita mustamsikin","kaset trio the kids","kaset mogi darusman","kaset dina mariana","kaset nicke","kaset hedicks","kaset sm recording","kaset mesra recording","kaset amudas","kaset begadang","kaset rollies","kaset nidya sisters","kaset swaddhitra","kaset maribaya","kaset de prins","kaset exsamasist","kaset anita anggoman","kaset sylado","rak kaset"]'
  BLACKLIST: '["hetty","erwin","cd","vinyl","compact","utopia","iem","honda"]'
  DB_HOST: "mariadb"
  DB_USER: "tokpedsniper"
  DB_NAME: "tokpedsniper"
