apiVersion: v1
kind: Secret
metadata:
  name: bot-secret
  namespace: tokped-sniper
type: Opaque
stringData:
  BOT_TOKEN: "your-discord-bot-token"       # change this
  CHANNEL_ID: "your-discord-channel-id"     # change this
  OWNER_ID: "your-discord-owner-id"         # change this
  DB_PASSWORD: "tokpedsniper"               # must match mariadb-secret.password
