apiVersion: v1
kind: Secret
metadata:
    name: bot-secret
    namespace: tokped-sniper
type: Opaque
data:
    BOT_TOKEN: ENC[AES256_GCM,data:E9o9gtaZ4tbtuuI7yH7IWRejNQw+N1VzPBTWQZ/LymgMrD2aOf8VrtPuKztrrtdXlGOyOlYZ6HuFj7GBoJtxdMq/2Khpi+10Wmgu5gJ8RR+V1/2jOtJAXuIh4Y5EuXmM,iv:fTaSTRIH/qJPXprf1Zo5lvrKTCbnUIa/fRBqzhM/AnE=,tag:8wkfqD+c6xvglTId+xEeYg==,type:str]
    CHANNEL_ID: ENC[AES256_GCM,data:RLUWhbo39Qpmn+ewHT7M4Bzb1lbgp187MhQ0zA==,iv:XArDXiOxnrlZcuH/nkEOzwPpBCJZGuE6RA2/L/7bG5s=,tag:mnsKiRpsYemI7Jk+J1x3kA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:q+W+1ggc0Op4d8C3wd2D0O9WkbStGS+x+dhCPBka4WA=,iv:o4Ey6waDUZmrVqHRY1/gwdBwhvpxUCCaQWC/nZxcEGI=,tag:efQOl8BD4SAD9nUrICElpw==,type:str]
    OWNER_ID: ENC[AES256_GCM,data:TcLGfg8gZPUhOErCgExAdaWLlV0jEA/b,iv:Q/cUIkwYhdf6pJZFDFxo6UhQgU26jspmO8wits0cVLA=,tag:WR11XOWCFRMz/SbttCkFTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbHIwVmVuTlIyRUNETmU1
            bVkyRWo0MkIvbnlsLy9LWnhaZ2pEQ3JQMkJFCkZ1Z2U5N2NVZFVDTUhTSTlLQjc5
            OG1BWEN1T2t1UGNHZzFZeHdSb2hla2cKLS0tIDRoTFlZUDdySTFWakdzZ25reUpx
            bDdpOGh5Y2tKTkF3N2F5Qk91Y2FiQXcKQTwZnCtRfi+NwJbSOHUSOya2GGWI97JF
            XC/g0nmn9yJgxni0S79LAHLKdiKzq1OXaRWo4AlO1Khi8V+fYPWCyw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:17:36Z"
    mac: ENC[AES256_GCM,data:wI62iO4kse/ijKfuR1PAqV6sElCdUnB680yjwqIjhQQ6i6rr5kjJTGNcLI0hlwTBvgtDZyeW/352WQzIH3u5nsFvF83vWQ0sgZm87Dn8Rq/J+CX1xoWUmvWmFXldT5zTRQC3luqlzUqKVvYpO7eBh87VDxwgX5A5Bo6tH7E8lTc=,iv:gb5WqJjinSIJKV4ALqk/NwmMviaysAOwp2YU8XX+IL0=,tag:dGPHLTzKmPhc8I+9aJZFlA==,type:str]
    version: 3.13.3
