apiVersion: v1
kind: Secret
metadata:
    name: irnusdl-secret
    namespace: irnusdl
type: Opaque
data:
    DJANGO_SECRET_KEY: ENC[AES256_GCM,data:XbyG1BwKAB5qI5ZBGHr6cUgOAKc7ZP+7YEyz3EMnpgfbqLb2XXxlIt6joP2jGWyYTuQ/mxsonzCHRs3rjj+dZ75FldPXvErsyD3RkXr40PCLRjBw3+ctxKp4tfs=,iv:IkdiwgOFNtSdl1OqDLLC/6+dYZKNlOPx1KKiBtMjM+Y=,tag:VXZQ1hLQtKi1OJIM50XekQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcWk3R1NPWGR2YkQ2eE1l
            amo1eFp5RzR3N0lTVHYveEgvcitlSVA5ZFhZCmxsWk5lUGpSN0JnL2gvT1lnZTF2
            S2w2SkMyOHdmZHNMdGVOdzVOblZ3dTAKLS0tIFpJQ244V09pOFYvbWJJSGdVYkxp
            V2oyVnRPTHFRcWpjUkVvdnV6RGlmNU0K1ItuoJc0awDkBcZJKKTVIfIkRRgwUfKm
            5YDFN5QNmAZEEaHDvVx27Gg9ffEJRIoUtT16s0+SS9yHCDndlAaVYQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:17:31Z"
    mac: ENC[AES256_GCM,data:Ff4YBmJ8tBOml69YYzU/9pOwFhJpjg3NrdMjg9iTCxCRBraq8yxVQC/t9iygf7FWF0MRVbBmydvQ2BbD3mpfpKq6dv/Uw8V7lzYZztL+OKGbpeL3v/T6SeQgzDpW2SkhIRyfnSX9nvtSVdrOWVTgEkTXaJcYw09LeyWR6yn5CgA=,iv:dnvJEhwDyiNN4y2r1E5K0uSXK3XnWyE/0lrQwkdIJ7c=,tag:4JxVIqmktSnS+ZqphVvlFA==,type:str]
    version: 3.13.3
