apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: irnusdl
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:k73by4icxkJ1htk5igle5KyzHyTk3G32Ft3VRZVAZj06enSl5jk6d+Whd7QAuKFfuleQ2kq5sh5I94NrXwPRm5e4WTLTq3/xDFhOqNGRhWzVDiMyDx/b9UGxCtcCw9CUz6qJTSRS2U38zFKJLW5e/v6AJjH7yo3lsLJMmRnMQ91+/A41mmel1C1tRA4Hby+FGa5rDkVB5iD0ScyiHgpBXqQi+B5ME/+gmeMfz0PrCX7ermCUF+4HDmLQxkGEAFnUIa29EJkJDhlluwrQC1xaYqO0oSXF/kvCAbh40iWxsGA02iLLjIhe/4IgJ3ppLefO,iv:0qjUY7tT+Q1J3eIfnS3UGnv6or2txpiv5JtMIP/c+BM=,tag:3ULSJCIN6ke6wp7ewdKqIg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOYnUyNTVWYjg2RzF2MlR6
            K1BzV3FIL2NrL0IyKzdFWEZEZzFxVmRGWVM0CjRIR3lVSjk0Z1hmc2NRNVcrUnVk
            K0lzNGloQ3ZMZzhESlVXV2RjUXJYcEkKLS0tIFhZLzRyd2tCMzVJeExQdUhqM0ZE
            UXlPSXFBZnlIa2ZIeXdZLzRSOWVlQlEK9l/mm4Gr6PxjJwIn+xRvYrv4qdrV3bdL
            2jMAme/LIqN1OIniQhwHO6Dv6JrVB/3d8XWD+bPQ0oSQiQHJN1S3IQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:17:32Z"
    mac: ENC[AES256_GCM,data:P+UOXqIURzpyF70hvMCtqTIvUPin6HHWc0KuYMDYxhN0UTRSixEJKePl18IZXx22zUP+jl4SF0dm08//EjfRiEYt/8bIVE1arqcM+LejSI4j9XddBp3ZlG6uyi/xrmGK8W0q4FL3M6p69DSxseb3EL2S8aWmXWFEIcftcKoTBgg=,iv:87CCPkVlLwBTCMdFtayUjFXjcMqn4hSfvcUA4Y3fPjs=,tag:wr1CXXoJm6Lg88Sa8P4bQg==,type:str]
    version: 3.13.3
