apiVersion: v1
kind: Secret
metadata:
    name: ghcr-secret
    namespace: slickerius-archive
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:FNRlGIsQQHNfGDFscB8O8nq/g177LsbyyLnKPrWxOM7gHDH+8kGCL0ov7asXoBuf2GFq46MfFkZ20i3vdsjo/u2RX8IIPsbUBlWtIlRjjrJTTF2PUR5vPIHW0a2aWiWlaJl1Nv3+EUxjYezwitwfLVGZtOOzkt1lhu9RknOMLuM29WRlXfLr9jiquskbOXxa0s5hdLN7i4kGmiWvr7GvCdTjlh9XkHSO1AioajFHSGvexRYoW7gZL8VqIvXHHZILXrRgc8C65wtxTeO9P91K9T/2xbXjbxlSRkFVx2Yz8bcu8ZV7p4T7RgAbDkscfDd3,iv:I22cviwCkMN6CWMfQzf6NLYJ1/K1KCfQxtLy/OQa70k=,tag:TEPK77mLF9JfmADvGqMt6Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwejFULzNRUE5VUG8xNVkr
            OTMrUjdsNGlTNFVxbDlTRzUxaUU2WU9RYlhzCkdaTDFXTHBhKzFldS9HeTNuQ3NZ
            NG1LVFNITVpmWEIrZktHekdIa01LQTQKLS0tIHE5RnBycWRVcmRuTitRWjFXMUZu
            b1I3UUxOajBBcGlDOG9sejdWQWV0bHcKrmGE8F6ymkxZFT+G8lIb3rDyMXv/M1M7
            FqTM909mhIEtJOTk+aIv6AbsFX75arbxoaUgpUzuneS/rs589QT7CQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:17:33Z"
    mac: ENC[AES256_GCM,data:qo1s8/J5661Q9cn1Z+xA9CNyD1DGyAODJ5glqvG58y30SG5lELKVK+EVmeGt7831NkdhR4Bhkmv99xN7g9BVYS6eP/s4Kw2tfhv957sSh5yL3B1IhsNK9aOuAuKY3H7u3XtzEuNGO59R1SQV7xN4R6Tjp5QQmIc6KLkEXhSgRsI=,iv:P+TOFbmTn/bv2UxnjpOUnVHt3o11Afq2tJlqZO9yl3E=,tag:I5yhQ/3ruUPsJ/6AA9bcqg==,type:str]
    version: 3.13.3
