apiVersion: v1
kind: Secret
metadata:
    name: healthcheck-secret
    namespace: slickerius-archive
type: Opaque
data:
    DISCORD_WEBHOOK_URL: ENC[AES256_GCM,data:qhuLjVIPyfg07DH0rHoU/2heB5+9Ea1Yu9lbsA1CU3e8dHYF03iVfB1NAZgXYmcPIFhm7zeppqFBNDGQVvuSMlDAmatUkzfpzBjvzjj/TfPwDSlRKIl6rT4snXNrynLyzN+IYsw8VmiFDvjk+pjMJJs7EKKC8XcVuZ3e4P99JuvZ8hVSDRW6lAkobAKq4+gm111ea05Zlk/KftRJcrN13oO5e9g=,iv:BGXv/xytjCiFPMmO+dUh+CYsYs47WZE9DOt2j506yxw=,tag:ZkFm8UnLFhUypyGLzAV8zw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKK01FUHBORm81ZmRuSDFC
            RFZtN3VackJOVTdrc0NhdVBGOS95NlA3UlZRCiszeGROK094dE5yZ3NIR0cvd01H
            MXVqcm94eSttdnpGMHE5ZlBaS2d6cVUKLS0tIGZPT296ZzV3Wk9uWDFONmxUOGZZ
            VlQ3ZzlsNGNSZCtINUtjUmszbk9Ca0kKkYaiVX6HG7gYDXQtZgPO9roAzRukcjmV
            uBmyDtw18xvpPn7KrDfrFXUK3gCdB+t92roeiRwR9KvFQs/DguNbLg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:17:35Z"
    mac: ENC[AES256_GCM,data:/HHsl8nwMREs+7MN4h6/8Jimc+bHSSasOpngyOpt96ies10e4k3LCtm+aS+jlZOk+ZM7909Kd8zKPP+HVAT/Y1CUTXXOEzLAuEZvtbJpqf83TqV3S/QdrVUrKC8aBwrzsTIpx0KaPRTh8IqbsMZjKnZAncvBd526kb61tVkTTUc=,iv:pdTQjkPAoWsAjpuSdpahUSgJ4jmDsDPVeaOlBRE5rL4=,tag:Xdj6dtMrf6p05ndic1ANvw==,type:str]
    version: 3.13.3
