apiVersion: v1
kind: Secret
metadata:
    name: strapi-secret
    namespace: slickerius-archive
type: Opaque
data:
    ADMIN_JWT_SECRET: ENC[AES256_GCM,data:NaqeqaB1cED7UBi6s1N36Uravka5iYk3Sk2YXCfVs60=,iv:I4TUT0qsJ8cv50GyHIMNURMiR+Ho7QX89O0WG6koQp4=,tag:pSmx3bBc27zRrtrAVHrwAQ==,type:str]
    ADMIN_URL: ENC[AES256_GCM,data:pOw3aWaflpw=,iv:pk51bK7CHxIp6A3uWp6hwcO/oAPmUR5XWoO23cQ2FHE=,tag:brgMEUdhkJdOn15Sv3CAHg==,type:str]
    API_TOKEN_SALT: ENC[AES256_GCM,data:CTNYNT3JHOCOUxzdoDdIj+2d2SwM2T6fGM5NHxWWReA=,iv:H8C0joSZlWbMNHYWL5S9/lYdhHn1Tt0Bk9yT5GYb7Fc=,tag:88tFQ3NUN6IVGoMVIYleHQ==,type:str]
    APP_KEYS: ENC[AES256_GCM,data:535VHmiJXOdod3V3h8LMhewaJWKdOAGj0sWXqgAkCKvIP5K7lSBaNHZf/LxexA+NiyoaBg2ac5/mmf2IceY1ABPIPL+U9RYeXMuHCioibLg2S8Ksr+rM2lnuu5e3CnGkML6V4CmvZCEI69NE5K4jdTu/ZOsGi8HyQy8eqCRziRkw9Fgi,iv:EtmHQkd0B3+NbkFO9fUdRKqov2D+reqe1QYEXXKTQTE=,tag:rrnQgE98rzU9pHvo31M1zg==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SA1I7VWTq6Jg3eX5XUfzZTmONIhwWbe9pUn1gw==,iv:jnDk4hDk9HOrfOjh6xTAUY5YdknoGBfGQRdiGji0Ydo=,tag:qR4bgGdAVQI1awaJNdrdkw==,type:str]
    AWS_ACCESS_SECRET: ENC[AES256_GCM,data:KGuY03BxcjtBee0+bsGX37jjKsVZyK7i/3MSHON4iJrvwg47QHW2YQagKZ5ExQQQqA16jseUjUA=,iv:Q50RAO2JGz3sN9/wr/bUWQej4O9sa0BU6hUpxPqebSk=,tag:EOnn8SqmT460kDglAVk/Sg==,type:str]
    AWS_BUCKET: ENC[AES256_GCM,data:CY9QRs1W8i5uU900ExqUKZKt8vLnMlmTb45RCVVUb74=,iv:jeF54ucd6bKjS+KXOyYeT1Pp/S1b1ghfxUMHF4VOakk=,tag:AJSWO7LbBOoU2WXEpWkFKA==,type:str]
    AWS_REGION: ENC[AES256_GCM,data:Uilg8Egd1HZz7EEnaEU5aeo68aA=,iv:/SU6YgbLtYX8hsSLW7t6LFfhvfhA5CMYwA9tuST0GOA=,tag:rXTGUNbrjLT+Xn5bcFPtHw==,type:str]
    CDN_URL: ENC[AES256_GCM,data:2XNfM8pZGTruV2hY/1n+g63i6qEEhl9fnNp3bcC+EP/y3HpfziAVDH+Q4UI=,iv:zs7Bf5k0o/8sklGyHrBBvN6lZRqJpz0E2PHGuiK1f/I=,tag:84GdhGR643fdNRd6D98+9g==,type:str]
    ENCRYPTION_KEY: ENC[AES256_GCM,data:MjOydK+4DyA5vVDi+GaqnUJ0WEAYwcux8RlrrycMq5Y=,iv:hHIf2miYnwnjALDeMkAcxxlo61pRCY0/04uHUxksCHI=,tag:gXgdow/zqDwXQX5Clsb9oA==,type:str]
    GATE_COOKIE: ENC[AES256_GCM,data:+QtYBrVRzs/b1osrlIDhmoXfIXmKt/vUj9sGY5LtboBt0X5vPNLmpRzcwVXLYOEdN20em6+WCDfuxE8GKkYAbRGQF/Ue0s9NSz1tGn8gwbWtYfErbU5hyQ==,iv:IS5DVppTL44Uf3p6d5k+HakmwJGbWiSj40clKFqAZuo=,tag:rO/jtuyHzkChxZBtTCetzA==,type:str]
    GATE_PATH: ENC[AES256_GCM,data:RTODVN+L+O2CsDVUPTDhwJIK21f0ZI9IaN2v0C2MpxJOPow0IlLUIngpouSn2vVTGtS5Ip+hbMMIU6BOPdZRN5E3v1Z+bfopGekVuZJ+V2MoEXHsf5RSe9PZ2cXgsAnELimTt3kq2lIGLz4jY+QRQR0PgECrnH0k9Z5uYDcorvKBnP16s+XKFR0Nw6YIII9jxXqzE/12VAtOJ6F821yks8F7GvJobYQllhn2Pg==,iv:SSS0wn4u9tFz86ucSK4J0U/S+cWv+yysFoqUI6oCG4Q=,tag:u5vC3a2f+3muFzbJXNfMPA==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:c90rtSfa90uDFpyeEwXRp0uda2Wch50YZWf7w335E5E=,iv:uiSRhUCHGKvTwiYdDzd5bhuf/BjqRUpLKyFay5mVZAQ=,tag:oXSW+fIG3uYLQZxcfs8MPA==,type:str]
    TRANSFER_TOKEN_SALT: ENC[AES256_GCM,data:BJdRlpHmCnI+EVyZ+GPv/sX6QuxfISLWPZAZIcmm6+M=,iv:TdmfO9v8VY8wOLNwTdC4YSzkJbeXcGq/dD1QdkFamik=,tag:NEfB2vzy5I5CQ/S8iBUrVA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGWW45aldGUWJESUVCc1FK
            cEZpeTVraGhlM2puL0dBQkplNVE0K3kvMmlJCjM4Q0xDWUJRaTBXZ3ZpcFhxUzdI
            S1NkRzJ3QTFieVRLdExaOGZVTjFWbWsKLS0tIGE1bjRadXZQandsY3pWakEvRGlT
            MXN0ajBMMTA3UmczTExwM1V2T3IwN0kKWsxFBN9xlBO3/ae6OZt/xUXBQZCdYI6Y
            1mtGheqiGn89cEGgNLGeO2TTexKRYGsfZG2ae7sYN/TuDaXP7ajpKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1g6g74levnaafllhysdxsp5ufujmx36ru6dt227ymxtj79f265yuqhhknv2
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-05T16:17:33Z"
    mac: ENC[AES256_GCM,data:PF1I5DsfoTZVTOH2xMzrdZzCKSFFmpnxyrXyRBYxj+WyKj4IPkc57M+BK7zmfAKXnwPiM97UV/ZUSZgDPiL/z8LO3uas8Ga+FrGTDFLV+cpBQnIvGNe2xEM9/Rq4EW/SGRR9ybTRhfBSL2oN3JRN+7UXzvBvvV0rLmtFTP6P+W0=,iv:Vm+nJMO/JE2a7ApbHsWB73vOe1xQurgZNti0Tam+D6k=,tag:Z+Q+OZu073F/GY5yOEWOBQ==,type:str]
    version: 3.13.3
