apiVersion: v1
kind: Secret
metadata:
  name: strapi-secret
  namespace: slickerius-archive
type: Opaque
stringData:
  APP_KEYS: "changeme"           # comma-separated base64 keys
  API_TOKEN_SALT: "changeme"
  ADMIN_JWT_SECRET: "changeme"
  TRANSFER_TOKEN_SALT: "changeme"
  ENCRYPTION_KEY: "changeme"
  JWT_SECRET: "changeme"
  AWS_ACCESS_KEY_ID: "changeme"
  AWS_ACCESS_SECRET: "changeme"
  AWS_REGION: "changeme"
  AWS_BUCKET: "changeme"
  CDN_URL: "changeme"
