apiVersion: v1
kind: Secret
metadata:
  name: slickerius-archive-tls
  namespace: slickerius-archive
type: kubernetes.io/tls
data:
  tls.crt: ""  # base64 of fullchain.pem
  tls.key: ""  # base64 of privkey.pem
